# Generated by Django 5.0.6 on 2026-09-04 21:24

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', validators=[config.validators.validate_image_size, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp'))]),
        ),
    ]
