# Generated by Django 6.0.7 on 2026-07-25 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'stock_ins',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='catalog.phonemodel')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockin')),
            ],
            options={
                'db_table': 'stock_items',
                'indexes': [models.Index(fields=['model'], name='stock_items_model_i_5cf249_idx'), models.Index(fields=['category'], name='stock_items_categor_196183_idx')],
            },
        ),
    ]
