# Generated by Django 5.2.17 on 2026-09-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
