# Generated by Django 5.2.17 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('password_request', 'Password Request'), ('failed_login', 'Failed Login'), ('new_return', 'New Return'), ('system_alert', 'System Alert'), ('note_shared', 'Note Shared')], max_length=20),
        ),
    ]
