# Generated by Django 6.0.7 on 2026-07-25 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('return_category', models.CharField(choices=[('display', 'Display'), ('battery', 'Battery'), ('charging', 'Charging'), ('camera', 'Camera'), ('speaker', 'Speaker'), ('software', 'Software'), ('network', 'Network'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleitem')),
            ],
            options={
                'db_table': 'returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='return_photos/')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='returns_app.return')),
            ],
            options={
                'db_table': 'return_photos',
            },
        ),
    ]
