# Generated by Django 5.0.6 on 2026-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
