# Generated by Django 5.0.6 on 2026-09-04 21:24

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns_app', '0002_alter_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnphoto',
            name='image',
            field=models.ImageField(upload_to='return_photos/', validators=[config.validators.validate_image_size, django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp'))]),
        ),
    ]
