# Generated by Django 5.0.6 on 2026-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_discount_saleitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='imei',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
