# Generated by Django 5.2.17 on 2026-09-11 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_stockitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('business_name', models.CharField(max_length=128)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], default='cash', max_length=20)),
                ('paid_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('loan_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loansale')),
            ],
            options={
                'db_table': 'loan_payments',
                'ordering': ['-paid_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loansale')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_sale_items', to='stock.stockitem')),
            ],
            options={
                'db_table': 'loan_sale_items',
            },
        ),
        migrations.AddIndex(
            model_name='loansale',
            index=models.Index(fields=['invoice_number'], name='loan_sales_invoice_6b6868_idx'),
        ),
        migrations.AddIndex(
            model_name='loansale',
            index=models.Index(fields=['created_at'], name='loan_sales_created_414170_idx'),
        ),
        migrations.AddIndex(
            model_name='loansaleitem',
            index=models.Index(fields=['imei'], name='loan_sale_i_imei_9c94b1_idx'),
        ),
    ]
